# ./utils/constants.py

from .helpers import get_addon_name

ADDON_NAME = get_addon_name()
CENTER_TEXT = "      "
OPEN_FOLDER_DELAY = 1.0
RE_CYCLES = "CYCLES"
RE_EEVEE = "BLENDER_EEVEE"
RE_EEVEE_NEXT = "BLENDER_EEVEE_NEXT"
RE_WORKBENCH = "BLENDER_WORKBENCH"
MODE_SINGLE = "SINGLE_FRAME"
MODE_SEQ = "SEQUENCE"
MODE_LIST = "FRAME_LIST"
RENDER_HISTORY_LIMIT = 30
ICON_COLLAPSED = "DISCLOSURE_TRI_DOWN"
ICON_EXPANDED = "DISCLOSURE_TRI_RIGHT"
ICON_OPTION = "DOWNARROW_HLT"
ICON_SYNC = "IMPORT"
