schema_version = "1.0.0"
id = "render_commander"
version = "1.2.3"
name = "Render Commander"
tagline = "Configure and export command-line render jobs"
maintainer = "Nadir Perazzo"
type = "add-on"
website = "https://github.com/n4dirp/Render-Commander"
tags = ["Render", "Import-Export"]
blender_version_min = "4.3.0"
license = ["SPDX:GPL-3.0-or-later"]
[permissions]
files = "Export script files and temp data"
clipboard = "Add data paths from the clipboard"